### ISSUE TITLE
Suggestion: expand the docs

### ISSUE THREAD

**Issue by mjkanji** [danielgafni/dagster-polars#13]
Hi there!

I've found this integration very useful and hope it'll get much more steam in the future. As such, it would be great to have expanded docs that ease new users into the following:

- how to use metadata to select columns in the InputContext
- how to use metadata to pass configuration options like compression type, etc., to the IO manager
- how the IO managers interact with lazy frames. For example, the `load_from_path` method of the base IO manager does a `collect()` if the input is a LazyFrame, but given that any upstream asset would have to be materialized to write to disk anyways, how would one receive a lazy frame as an input in the first place? This bit is rather ambiguous to me.
  - The `dump_df_to_path` function also only works with `pl.DataFrame`, but there is presumably a use case for the user simply returning a `LazyFrame` as the output of an asset. Perhaps it might be helpful to have a `collect()` in the `dump_df_to_path` (or the use of `sink_parquet`) for those scenarios?

**Comment by danielgafni** [comment]
Hey!
Thank you for the warm words, I'm glad it's useful to you.
Sure, I'll add more examples. 
Hopefully my answers here can help you too.

> how to use metadata to select columns

```python
@asset(
    ins={
        "upstream": AssetIn(metadata={"columns": ["a", "b"]})
    },
    ...
)
def downstream(upsream: pl.DataFrame):
    ...
```

> how to use metadata to pass configuration options like compression type


```python
@asset(
    metadata={"compression": "gzip"},
    ...
)
def downstream(upsream: pl.DataFrame):
    ...

> how the IO managers interact with lazy frames

Just specify `pl.LazyFrame` as type annotation in tour asset and `dagster-polars` will do the job. Copying the example from the README:

```python

@asset(io_manager_key="polars_parquet_io_manager")
def upstream() -> pl.DataFrame:
    df = ...
    return df


@asset(io_manager_key="polars_parquet_io_manager")
def downstream(upstream: pl.LazyFrame) -> pl.DataFrame:
    df = ...  # some lazy operations with `upstream`
    return df.collect()
```

For UPath-based IOMdanagers `dagster-polars` always first loads the upstream asset as `LazyFrame`. `.collect()` is called only if the user requested an eager frame. 

> Perhaps it might be helpful to have a collect() in the dump_df_to_path (or the use of sink_parquet) for those scenarios?

I agree. `dagster-polars` should also provide the ability to: 
 - choose `streaming=True|False`
 - choose `sink_parquet` / `.collect().write_parquet`
 ...
This logic may be different for different IOMangers (`sink_delta` doesn't exist).

**Comment by danielgafni** [comment]
Added some docs in #14
