### ISSUE TITLE
bump pendulum verison

### ISSUE THREAD

**Issue by Sage0614** [danielgafni/dagster-polars#59]
latest dagster version (1.6.5) now depends on pendulum 3.0, should bump pendulum version accordingly

**Comment by danielgafni** [comment]
Hey!

We also support older Dagster versions. They don't have this requirement, so I don't think dagster-polars should. 

It would be resolved correctly if you are using the latest Dagster version anyway.

**Comment by Sage0614** [comment]
I mean this package have this defined in pyproject toml:

[tool.poetry.dependencies]](https://github.com/danielgafni/dagster-polars/blob/d26dc024bfe913781fb394f9a7aff6327aa302b0/pyproject.toml#L41)

so it will done grade pendulum to 2.x if you use dagster 1.6.5,
and I suspect it will also block dagster to work with python 3.12
https://github.com/dagster-io/dagster/issues/17350

**Comment by danielgafni** [comment]
Oh, I see, thanks. Will fix.

**Comment by danielgafni** [comment]
`dagster-polars` has been merged into `dagster`'s main repo. The next release should not have the `pendulum` constraint.
